---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-default-conf
data:
  default.conf: |
    proxy_cache_path /tmp/cache levels=1:2 keys_zone=big_cache:500m;

    gzip_static  on;
    gzip on;
    gzip_min_length 50000;
    log_format  jsonlog escape=json
        '   {\"bytes_sent\":\"$bytes_sent\",\"date_gmt\":\"$date_gmt\",\"host\":\"$host\",\"query_string\":\"$query_string\",\"request_time\":\"$request_time\",\"request_uri\":\"$request_uri\",\"upstream_cache_status\":\"$upstream_cache_status\",\"uri\":\"$uri\"}';

    server {
        listen       9090;
        # error_log /tmp/error.log notice;
        access_log  /dev/stdout  jsonlog;
        listen       9090;
        # cache everything
        location / {
            proxy_buffering on;
            proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
            proxy_ignore_headers Set-Cookie;
            proxy_cache big_cache;
            proxy_cache_valid 1h;
            proxy_cache_methods GET POST;
            # below must match service name of kubecost
            proxy_pass http://kubecost-cost-analyzer:9090/;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubecost-cache-proxy
  labels:
    app: kubecost-cache-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubecost-cache-proxy
  template:
    metadata:
      labels:
        app: kubecost-cache-proxy
    spec:
      containers:
      - name: kubecost-cache-proxy
        image: nginxinc/nginx-unprivileged
        imagePullPolicy: IfNotPresent
        ports:
        - name: cache-proxy
          containerPort: 9090
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-default-conf
          readOnly: true
      volumes:
      - name: nginx-default-conf
        configMap:
          name: nginx-default-conf
          items:
          - key: default.conf
            path: default.conf
---
apiVersion: v1
kind: Service
metadata:
  name: kubecost-cache-proxy
spec:
  ports:
    - name: cache-proxy
      protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: kubecost-cache-proxy
  type: ClusterIP