
{{- if .Values.cacheProxy.enabled }}
{{- $serviceName := include "cost-analyzer.serviceName" . -}}
{{- $nginxPort := .Values.service.targetPort | default 9090 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cache-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
    default.conf: |
        proxy_cache_path /tmp/cache levels=1:2 keys_zone=big_cache:500m;

        gzip_static  on;
        gzip on;
        gzip_min_length 50000;
        log_format  jsonlog escape=json
            '   {\"upstream_cache_status\":\"$upstream_cache_status\",\"bytes_sent\":\"$bytes_sent\",\"date_gmt\":\"$date_gmt\",\"host\":\"$host\",\"query_string\":\"$query_string\",\"args\":\"$args\",\"request_time\":\"$request_time\",\"request_uri\":\"$request_uri\",\"uri\":\"$uri\"}';

        upstream kubecost-frontend {
            server {{ $serviceName }}.{{ .Release.Namespace }}:{{ $nginxPort }};
        }

        server {
            listen      {{ $nginxPort }};
{{- if .Values.kubecostFrontend.ipv6.enabled }}
            listen [::]:{{ $nginxPort }};
{{- end }}
            # error_log /tmp/error.log notice;
            access_log  /dev/stdout  jsonlog;
            # do not cache unless matching specific location block below
            location / {
                proxy_pass http://kubecost-frontend;
                add_header X-Cache-Status $upstream_cache_status;
            }

            location /model/allocation {
                proxy_buffering on;
                proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
                proxy_ignore_headers Set-Cookie;
                proxy_cache big_cache;
                proxy_cache_valid any {{ .Values.cacheProxy.cacheDuration }};
                proxy_cache_methods HEAD GET POST;
                proxy_pass http://kubecost-frontend;
                add_header X-Cache-Status $upstream_cache_status;
            }

            location /model/assets {
                proxy_buffering on;
                proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
                proxy_ignore_headers Set-Cookie;
                proxy_cache big_cache;
                proxy_cache_valid any {{ .Values.cacheProxy.cacheDuration }};
                proxy_cache_methods HEAD GET POST;
                proxy_pass http://kubecost-frontend;
                add_header X-Cache-Status $upstream_cache_status;
            }
            location /model/savings {
                proxy_buffering on;
                proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
                proxy_ignore_headers Set-Cookie;
                proxy_cache big_cache;
                proxy_cache_valid any {{ .Values.cacheProxy.cacheDuration }};
                proxy_cache_methods HEAD GET POST;
                proxy_pass http://kubecost-frontend;
                add_header X-Cache-Status $upstream_cache_status;
            }
            location /static {
                proxy_buffering on;
                proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
                proxy_ignore_headers Set-Cookie;
                proxy_cache big_cache;
                proxy_cache_valid any {{ .Values.cacheProxy.cacheDuration }};
                proxy_cache_methods HEAD GET POST;
                proxy_pass http://kubecost-frontend;
                add_header X-Cache-Status $upstream_cache_status;
            }
        }
{{- end }}
