
{{- if .Values.cacheProxy.enabled }}
{{- $serviceName := include "cost-analyzer.serviceName" . -}}
{{- $nginxPort := .Values.service.targetPort | default 9090 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-cache-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
    default.conf: |
        proxy_cache_path /tmp/cache levels=1:2 keys_zone=big_cache:500m;

        gzip_static  on;
        gzip on;
        gzip_min_length 50000;
        log_format  jsonlog escape=json
            '   {\"bytes_sent\":\"$bytes_sent\",\"date_gmt\":\"$date_gmt\",\"host\":\"$host\",\"query_string\":\"$query_string\",\"request_time\":\"$request_time\",\"request_uri\":\"$request_uri\",\"upstream_cache_status\":\"$upstream_cache_status\",\"uri\":\"$uri\"}';

        upstream kubecost-frontend {
            server {{ $serviceName }}.{{ .Release.Namespace }}:{{ $nginxPort }};
        }

        server {
            listen       {{ $nginxPort }};
{{- if .Values.kubecostFrontend.ipv6.enabled }}
            listen [::]:{{ $nginxPort }};
{{- end }}
            # error_log /tmp/error.log notice;
            access_log  /dev/stdout  jsonlog;
            # cache everything
            location / {
                proxy_buffering on;
                proxy_ignore_headers Expires Cache-Control X-Accel-Expires;
                proxy_ignore_headers Set-Cookie;
                proxy_cache big_cache;
                proxy_cache_valid 1h;
                proxy_cache_methods GET POST;
                # below must match service name of kubecost
                proxy_pass http://kubecost-frontend/;
            }
        }
{{- end }}
